# Generated by Django 4.2.5 on 2023-09-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_alter_blog_options_blog_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={},
        ),
    ]
