# Generated by Django 4.2.5 on 2023-09-15 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0003_alter_blog_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="updated_at",
            new_name="upload_to",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="description",
        ),
        migrations.AddField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(upload_to="blog"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
