# Generated by Django 4.2.5 on 2023-09-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0004_rename_updated_at_blog_upload_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
